### ISSUE TITLE
[Bug] SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by ravensorb** [Venryx/file-syncer#1]
Not sure if I am using the tool wrong or if there is an issue with the current version.

Command
```
npx file-syncer --from src/.default/default/src/root/opt/setup/common --to src/apps/data/mongodb/src/mongodb/root/opt/setup/common
```
Error
```
/home/user/source/github/docker-apps-source/node_modules/file-syncer/Source/Utils.js:37
	const arg_nextIsValue = argIndex != -1 ? !args[argIndex + 1]?.startsWith("--") : false;
	                                                             ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/user/source/github/docker-apps-source/node_modules/file-syncer/Source/index.js:6:77)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by Venryx** [comment]
Perhaps using an old version of NodeJS that doesn't support the `?.` operator... which version are you using?

**Comment by ravensorb** [comment]
Excellent question -- looks like I am on 8.5.1 (on Linux Mint 21.2).  I take I should update it?

**Comment by Venryx** [comment]
Updating NodeJS to a recent version should fix it.

At least it should, since that operator works in the NodeJS here (away from desktop atm): https://www.jdoodle.com/execute-nodejs-online/

(I've also of course used file-syncer on my PC before, but haven't recently, so unsure if some other issue might be hit.)
